openai:
  api_key: "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"

anthropic:
  api_key: "your-anthropic-api-key"

deepseek:
  api_key: "sk-e2952161cd614ff5b7012c4309d6ba1e"

siliconflow:
  api_key:  "sk-zjqzekkadpjktuzejrnpcivntunbjuxxfneqdtwlgklftieg"

huggingface:
  api_key: "your-huggingface-api-key"

ali:
  api_key: "sk-a30a03a5670a4e46a8b2f8decf130411"

translator:
  api_key: "1B7xemgzwjJoxaTc8CODXJ63l57g8YH1GO5e8CskVgAzAwRCbpLAJQQJ99BBAC3pKaRXJ3w3AAAbACOGgEME"
  endpoint: "https://api.cognitive.microsofttranslator.com/"
  location: "eastasia"
